<?php

namespace OC\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function findByUsernameOrEmail( $username ) {
		return $this->createQueryBuilder( 'u' )
		            ->andWhere( 'u.username = :username OR u.email = :username' )
		            ->setParameter( 'username', $username )
		            ->getQuery()
		            ->getOneOrNullResult();
	}

	public function findByEmail($email)
	{
		return $this->createQueryBuilder('u')
	        ->andWhere('u.email = :email')
	        ->setParameter('username', $email)
	        ->getQuery()
	        ->getOneOrNullResult();
	}

	public function findByRole($role)
	{
		$qb = $this->createQueryBuilder('u');
		$qb->select('u')
		   ->leftJoin('u.groups', 'g')
		   ->where($qb->expr()->orX(
			   $qb->expr()->like('u.roles', ':roles'),
			   $qb->expr()->like('g.roles', ':roles')
		   ))
		   ->setParameter('roles', '%"'.$role.'"%');

		return $qb->getQuery()->getResult();
	}
}
