<?php

namespace OC\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function findByUsernameOrEmail( $username ) {
		return $this->createQueryBuilder( 'u' )
		            ->andWhere( 'u.username = :username OR u.email = :username' )
		            ->setParameter( 'username', $username )
		            ->getQuery()
		            ->getOneOrNullResult();
	}

	public function findByEmail($email)
	{
		return $this->createQueryBuilder('u')
	        ->andWhere('u.email = :email')
	        ->setParameter('username', $email)
	        ->getQuery()
	        ->getOneOrNullResult();
	}

	public function findByRole($role)
	{
		return $this->createQueryBuilder('u')
            ->where('u.role = :role')
            ->setParameter('role', $role)
            ->getQuery()
            ->getOneOrNullResult();
	}
}
