security:

    encoders:
        OC\UserBundle\Entity\User: bcrypt

    providers:
        database_users:
            entity: { class: OC\UserBundle\Entity\User, property: email }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            guard:
                authenticators:
                    - security.login_form_authentication
                    - security.change_password_via_token_authentication

                entry_point: security.login_form_authentication
            logout:
                path: /deconnexion
                target: /

    role_hierarchy:
        ROLE_ADMIN: [ROLE_ADMIN, ROLE_USER]
        ROLE_USER: [ROLE_USER]

    access_control:
        - { path: /inscription, role: IS_AUTHENTICATED_ANONYMOUSLY  }
        - { path: /login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /profil, role: ROLE_USER }
        - { path: /admin, role: ROLE_ADMIN }
