# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    oc_fidelite.points_fidelite:
        class: OC\FideliteBundle\Services\PointsFidelite

    oc_fidelite.vente_manager:
        class: OC\FideliteBundle\Manager\VenteManager
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@oc_fidelite.points_fidelite"
            - "@form.factory"
            - "@request_stack"

    oc_fidelite.client_manager:
            class: OC\FideliteBundle\Manager\ClientManager
            arguments:
                - "@doctrine.orm.default_entity_manager"
                - "@form.factory"
                - "@request_stack"
                - "@service_container"

