<?php

namespace OC\FideliteBundle\Repository;

use Doctrine\ORM\NoResultException;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllClientsParOrdre($client)
    {
        $queryBuilder = $this->createQueryBuilder('a')
            ->select('a.id','a.nom', 'a.prenom', 'a.societe', 'a.dateNaissance')
            ->add('orderBy','a.nom ASC, a.prenom ASC, a.dateNaissance ASC')
        ;

        try {
            $query = $queryBuilder
                ->getQuery()
                ->getResult();
        }   catch (NoResultException $e) {
            $query = 0;
        }

        return $query;
    }
}
