<?php

namespace OC\FideliteBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * VenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VenteRepository extends EntityRepository
{
    public function getNbrVentesRestantes()
    {
        $queryBuilder = $this->createQueryBuilder('a')

        ;

        try {
            $query = $queryBuilder
                ->getQuery()
                ->getResult();
        }   catch (NoResultException $e) {
            $query = 0;
        }



        return $query;
    }
}
