<?php

namespace OC\FideliteBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * VenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VenteRepository extends EntityRepository
{
    public function getNbrVentesRestantes($vente)
    {
        $queryBuilder = $this->createQueryBuilder('a')
            ->select('a.id', 'COUNT(a.client_id) as nbr')
            ->innerJoin('a.client', 'clt')
            ->addSelect('clt')
            ->where('$clientId = a.client_id = ?')
        ;

        try {
            $query = $queryBuilder
                ->getQuery()
                ->getResult();
        }   catch (NoResultException $e) {
            $query = 0;
        }
        return $query;
    }

}
